name: nussl-models

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.7
  - pytorch
  - ffmpeg
  - sox
  - resampy
  - pip
  - redis
  - pip:
    - scaper
    - git+git://github.com/interactiveaudiolab/nussl
    - git+https://github.com/google/gin-config
    - IPython
    - ffmpy
    - p_tqdm
    - nvgpu
